# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-10 22:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemsShop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pech',
            name='manufacturer',
            field=models.CharField(blank=True, choices=[('Harvia', 'Harvia'), ('Tylo', 'Tylo')], max_length=100, null=True, verbose_name='Производитель'),
        ),
    ]
